version: 0.0
os: linux
files:
  - source: /target/aws-cicd-demo.war
    destination: /opt/tomcat
hooks:
  BeforeInstall:
    - location: echo "Should install tomcat"
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

